config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'location' => 'users#location'

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	validates :first_name, presence: true, length: { maximum: 50 }
	validates :last_name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, 
					  uniqueness: { case_sensitive: false }

	has_secure_password

	validates :password, length: { minimum: 6 }
	validates :mobile_number, length: { minimum: 10, maximum: 10}
	geocoded_by :location
	after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
	end

	def destroy
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      flash[:success] = "Welcome to the Chirp App!"
  		redirect_to users_path
  	else
  		render 'new'
  	end
  end

  def index
  	@users = User.all
    @hash = Gmaps4rails.build_markers(@users) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      marker.infowindow user.first_name
    end
  end

  def location
    @users = User.all
    @hash = Gmaps4rails.build_markers(@users) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      marker.infowindow user.first_name
    end
  end

  def show
  	@user = User.find(params[:id])
  end

  private

  	def user_params
  		params.require(:user).permit(:first_name, :last_name, :mobile_number, :email, :password, :password_confirmation, :location)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title='')
		base_title = "Communicating Website"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user)
	    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
	    image_tag(gravatar_url, alt: user.first_name, class: "gravatar")
  	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<p>&copy; Chirp 2016 - All Rights Reserved</p>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "News", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to image_tag("chirp.png", alt: "Chirp logo"), root_path, id: 'logo' %>
    <%= link_to "Chirp", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Users",  '#' %></li>
        <li><%= link_to "Locate Users",  '#', 'data-no-turbolink' => true %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "Log in", signin_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |msg, des| %>
		<div class="alert alert-<%= msg %>"><%= des %></div>
	<% end %>
	<%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
	    <div class="alert alert-error">
	      The form contains <%= pluralize(@user.errors.count, "error") %>
	    </div>
	    <ul>
	    	<% @user.errors.full_messages.each do |msg| %>
	    		<li>* <%= msg %></li>
	    	<% end %>
	    </ul>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About Us") %>
<h1>About Us</h1>
<p>
  The <a href="http://thawing-garden-32754.herokuapp.com">Chirp app</a>
  is a social networking website. Where you can follow the users of the website who have already registed with us. This
  is highly meant for communication purposes.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact Us") %>
<h1>Contact Us</h1>
<p>This is the contact page for the website. It is still under developement. Please give us some time and get back here later.</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Welcome to Chirp Help Center</h1>
<p>This page is currently under developement. We will try our best to finish this page as early as possible and provide full support to the users in an efficient way.</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center hero-unit">
  <h1>Welcome to the Chirp App</h1>

  <h2>
    This is the home page for the
   <%= link_to "Chirp Application", users_path %>.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="span6 offset3 col-md-6 col-md-offset-3">
  	<% @users.each do |i| %>
  		<%= gravatar_for i %>
  		<%= i.first_name %>
  		<%= i.last_name %><br>
  	<% end %>
  </div>
</div>

app/views/users/location.html.erb
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->


<div style='width: 800px;'>
  <div id="map" style='width: 700px; height: 400px;'></div>
</div>

<script type="text/javascript">
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
	  markers = handler.addMarkers(<%= raw @hash.to_json %>);
	  handler.bounds.extendWith(markers);
	  handler.fitMapToBounds();
	});
</script>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3 col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= render 'shared/error_messages' %>

      <%= f.label :first_name, "First Name" %>
      <%= f.text_field :first_name, placeholder: "First Name", class: 'form-control', autofocus: true %>

      <%= f.label :last_name, "Last Name" %>
      <%= f.text_field :last_name, placeholder: "Last Name", class: 'form-control' %>

      <%= f.label :mobile_number, "Mobile" %>
      <%= f.text_field :mobile_number, placeholder: "Mobile", class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, placeholder: "Email", class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, placeholder: "Password", class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: 'form-control' %>

      <%= f.label :location %>
      <%= f.text_field :location, placeholder: "Location", class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-lg btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.first_name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.first_name %>
        <%= @user.last_name %>
      </h1>
    </section>
  </aside>
</div>